"""init

Revision ID: 6c366278fad5
Revises: 6c728d4a103a
Create Date: 2024-02-29 10:26:18.624170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c366278fad5'
down_revision = '6c728d4a103a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
