"""init

Revision ID: 775d70beef84
Revises: 4a658481dab9
Create Date: 2024-03-08 15:01:03.364801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775d70beef84'
down_revision = '4a658481dab9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
