"""init

Revision ID: 4a658481dab9
Revises: 6b65578b7f5f
Create Date: 2024-03-08 14:57:59.829107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a658481dab9'
down_revision = '6b65578b7f5f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
