"""Change column data type

Revision ID: 15cb4e61dde3
Revises: 
Create Date: 2024-02-17 14:46:32.588970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15cb4e61dde3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alldata', sa.Column('title', sa.String(length=100), nullable=True))
    op.drop_column('alldata', 'title1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alldata', sa.Column('title1', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('alldata', 'title')
    # ### end Alembic commands ###
