"""Change column data type

Revision ID: 683cff919fe2
Revises: 
Create Date: 2024-02-17 14:39:18.272875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '683cff919fe2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pid')
    op.drop_table('user')
    op.add_column('alldata', sa.Column('title1', sa.String(length=100), nullable=True))
    op.drop_column('alldata', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alldata', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('alldata', 'title1')
    op.create_table('user',
    sa.Column('userID', sa.INTEGER(), server_default=sa.text('nextval(\'"user_userID_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('userName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('birthDay', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('userID', name='user_pkey')
    )
    op.create_table('pid',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=55), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pid_pkey')
    )
    # ### end Alembic commands ###
