"""Change column data type

Revision ID: 6ecb92515efe
Revises: 3d42abb03325
Create Date: 2024-02-15 16:08:34.633445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ecb92515efe'
down_revision: Union[str, None] = '3d42abb03325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fid',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('userID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fid')
    # ### end Alembic commands ###
